# Generated by Django 3.0.6 on 2020-05-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='frequencyOfReoccurence',
            new_name='frequencyOfReoccurrence',
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
