# Generated by Django 3.0.6 on 2020-05-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200505_1121'),
        ('app', '0004_auto_20200506_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amountDue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amountPaid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amountOutstanding', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('orderStatus', models.CharField(choices=[(1, 'In Progress'), (2, 'Done'), (3, 'Cancelled')], default=1, max_length=250)),
                ('dateAndTimeOfOrder', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Menu')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Vendor')),
            ],
        ),
    ]
