# Generated by Django 3.0.6 on 2020-05-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentStatus',
            field=models.CharField(choices=[('Pre-Paid', 'Pre-Paid'), ('Paid', 'Paid')], default='Paid', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('In-Progess', 'In-Progress'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default='In-Progress', max_length=250),
        ),
    ]
