# Generated by Django 2.2.4 on 2020-05-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200504_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='bussinessName',
        ),
        migrations.AddField(
            model_name='vendor',
            name='businessName',
            field=models.CharField(default='Here', max_length=255),
            preserve_default=False,
        ),
    ]
