# Generated by Django 2.2.4 on 2020-05-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200505_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='businessName',
            field=models.CharField(max_length=255),
        ),
    ]
