# Generated by Django 2.2.4 on 2020-05-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200505_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth',
            old_name='isActive',
            new_name='active',
        ),
        migrations.AddField(
            model_name='auth',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auth',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
